version: "3.7"

services:
  db:
    container_name: ${PROJECT_NAME}_DB
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
    restart: always

  web: &web
    container_name: ${PROJECT_NAME}_backend
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8319
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./:/app
      - ./static:/home/app/web/static
      - ./media:/home/app/web/media
      - ./locale:/home/app/web/locale
    env_file:
      - .env
    ports:
      - 8319:8319
    depends_on:
      - db
      - redis

  daphne:
    <<: *web
    container_name: ${PROJECT_NAME}_ws
    command: python3 -m daphne -b 0.0.0.0 -p 8893 config.asgi:application
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.prod
    ports:
      - 8893:8893

  redis:
    container_name: ${PROJECT_NAME}_redis
    image: redis:6-alpine
    restart: always


volumes:
  postgres_data:
  static_volume: