# Generated by Django 4.2 on 2023-07-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0004_alter_driver_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="balance",
            field=models.IntegerField(default=100000, verbose_name="Driver Balance"),
        ),
        migrations.AlterField(
            model_name="driver",
            name="status",
            field=models.CharField(
                choices=[
                    ("In_Moderation", "In Moderation"),
                    ("Active", "Active"),
                    ("Blocked", "Blocked"),
                ],
                default="In_Moderation",
                max_length=256,
                verbose_name="Driver Status",
            ),
        ),
    ]
