# Generated by Django 4.2 on 2023-08-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0005_alter_driver_balance_alter_driver_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="car_number",
            field=models.CharField(max_length=8, unique=True, verbose_name="Car Number"),
        ),
    ]
