# Generated by Django 4.2 on 2023-09-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0006_alter_driver_car_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="city",
            field=models.CharField(
                choices=[
                    ("Namangan", "Namangan"),
                    ("Tashkent", "Tashkent"),
                    ("Toshkent", "Toshkent"),
                    ("Toshkent shahar", "Toshkent shahar"),
                    ("Namangan Viloyati", "Namangan Viloyati"),
                ],
                default="Namangan",
                max_length=256,
                verbose_name="City",
            ),
        ),
    ]
