# Generated by Django 4.2 on 2023-09-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0007_alter_driver_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="city",
            field=models.CharField(
                choices=[("Namangan", "Namangan"), ("Tashkent", "Tashkent")],
                default="Namangan",
                max_length=256,
                verbose_name="City",
            ),
        ),
    ]
