# Generated by Django 4.2 on 2023-08-26 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Promocode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "code",
                    models.CharField(max_length=255, unique=True, verbose_name="Code"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expired at")),
                (
                    "max_usage_count",
                    models.IntegerField(default=100, verbose_name="Maximum Usage Count"),
                ),
                ("money_amount", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Promocode",
                "verbose_name_plural": "Promocodegs",
                "db_table": "promocode",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="UserPromocode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "promocode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.promocode",
                        verbose_name="Promocode",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "UserPromocode",
                "verbose_name_plural": "UserPromocodes",
                "db_table": "user_promocode",
                "ordering": ("-id",),
            },
        ),
    ]
