# Generated by Django 4.2 on 2023-08-26 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="promocode",
            options={
                "ordering": ("-id",),
                "verbose_name": "Promocode",
                "verbose_name_plural": "Promocodes",
            },
        ),
    ]
