# Generated by Django 4.2 on 2023-09-02 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_alter_promocode_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpromocode",
            name="promocode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_promocode",
                to="common.promocode",
                verbose_name="Promocode",
            ),
        ),
    ]
