# Generated by Django 4.2 on 2023-09-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_alter_userpromocode_promocode"),
    ]

    operations = [
        migrations.CreateModel(
            name="FrontTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=511, verbose_name="Key")),
                ("text", models.TextField(verbose_name="Text")),
                ("text_uz", models.TextField(null=True, verbose_name="Text")),
                ("text_ru", models.TextField(null=True, verbose_name="Text")),
                ("text_en", models.TextField(null=True, verbose_name="Text")),
            ],
            options={
                "verbose_name": "Front Translation",
                "verbose_name_plural": "Front Translations",
                "db_table": "front_translation",
            },
        ),
    ]
