# Generated by Django 4.2 on 2023-09-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_fronttranslation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fronttranslation",
            name="key",
            field=models.CharField(max_length=511, unique=True, verbose_name="Key"),
        ),
    ]
