# Generated by Django 4.2 on 2023-07-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_first_name_remove_user_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Full Name"),
        ),
    ]
