# Generated by Django 4.2 on 2023-07-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(max_length=255, verbose_name="Full Name"),
        ),
    ]
