# Generated by Django 4.2 on 2023-07-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_location_city_alter_order_delivery_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="promocode",
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name="Promocode"),
        ),
    ]
