# Generated by Django 4.2 on 2023-07-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_alter_order_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="seat",
            field=models.CharField(
                choices=[
                    ("front_right", "FRONT RIGHT"),
                    ("back_left", "BACK LEFT"),
                    ("back_middle", "BACK MIDDLE"),
                    ("back_right", "BACK RIGHT"),
                ],
                max_length=256,
                verbose_name="Seat Choices",
            ),
        ),
    ]
