# Generated by Django 4.2 on 2023-07-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_alter_order_seat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="price",
            field=models.IntegerField(default=120000, verbose_name="Order Price"),
        ),
    ]
