# Generated by Django 4.2 on 2023-08-03 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0005_alter_driver_balance_alter_driver_status"),
        ("order", "0007_alter_order_status_request"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="seat",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="back_left_seat",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="back_middle_seat",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="back_right_seat",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="front_right_seat",
        ),
        migrations.AddField(
            model_name="order",
            name="back_left",
            field=models.BooleanField(blank=True, null=True, verbose_name="BACK LEFT"),
        ),
        migrations.AddField(
            model_name="order",
            name="back_middle",
            field=models.BooleanField(blank=True, null=True, verbose_name="BACK MIDDLE"),
        ),
        migrations.AddField(
            model_name="order",
            name="back_right",
            field=models.BooleanField(blank=True, null=True, verbose_name="BACK RIGHT"),
        ),
        migrations.AddField(
            model_name="order",
            name="front_right",
            field=models.BooleanField(blank=True, null=True, verbose_name="FRONT RIGHT"),
        ),
        migrations.AddField(
            model_name="order",
            name="number_of_people",
            field=models.IntegerField(default=1, verbose_name="Number Of People"),
        ),
        migrations.AddField(
            model_name="trip",
            name="client",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"type__in": ["PERSON"]},
                null=True,
                related_name="person_orders",
                to="order.order",
                verbose_name="Person Orders",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="driver",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="driver.driver",
                verbose_name="Driver",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="delivery",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"type__in": ["DELIVERY"]},
                null=True,
                related_name="deliveries",
                to="order.order",
                verbose_name="Delivery",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "ACTIVE"),
                    ("IN_PROCESS", "IN_PROCESS"),
                    ("COMPLETED", "COMPLETED"),
                ],
                default="ACTIVE",
                max_length=256,
                verbose_name="Status",
            ),
        ),
    ]
