# Generated by Django 4.2 on 2023-08-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0008_remove_order_seat_remove_trip_back_left_seat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="client",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"type__in": ["PERSON"]},
                related_name="person_orders",
                to="order.order",
                verbose_name="Person Orders",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="delivery",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"type__in": ["DELIVERY"]},
                related_name="deliveries",
                to="order.order",
                verbose_name="Delivery",
            ),
        ),
    ]
