# Generated by Django 4.2 on 2023-08-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0009_alter_trip_client_alter_trip_delivery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="back_left",
            field=models.BooleanField(default=False, verbose_name="BACK LEFT"),
        ),
        migrations.AlterField(
            model_name="order",
            name="back_middle",
            field=models.BooleanField(default=False, verbose_name="BACK MIDDLE"),
        ),
        migrations.AlterField(
            model_name="order",
            name="back_right",
            field=models.BooleanField(default=False, verbose_name="BACK RIGHT"),
        ),
        migrations.AlterField(
            model_name="order",
            name="front_right",
            field=models.BooleanField(default=False, verbose_name="FRONT RIGHT"),
        ),
    ]
