# Generated by Django 4.2 on 2023-08-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0010_alter_order_back_left_alter_order_back_middle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Document", "DOCUMENT"),
                    ("Money", "MONEY"),
                    ("Box", "BOX"),
                    ("Dishes", "DISHES"),
                    ("Secret", "SECRET"),
                ],
                default="Document",
                max_length=256,
                null=True,
                verbose_name="Delivery Type",
            ),
        ),
    ]
