# Generated by Django 4.2 on 2023-08-27 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_alter_promocode_options"),
        ("order", "0013_alter_order_delivery_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="promocode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.promocode",
                verbose_name="Promocode",
            ),
        ),
    ]
