# Generated by Django 4.2 on 2023-09-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0014_alter_order_promocode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="street",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Street"
            ),
        ),
    ]
