# Generated by Django 4.2 on 2023-09-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0015_alter_location_street"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="city",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Namangan", "Namangan"),
                    ("Tashkent", "Tashkent"),
                    ("Toshkent", "Toshkent"),
                    ("Toshkent shahar", "Toshkent shahar"),
                    ("Namangan Viloyati", "Namangan Viloyati"),
                ],
                default="Namangan",
                max_length=256,
                null=True,
                verbose_name="City",
            ),
        ),
    ]
