# Generated by Django 4.2 on 2023-09-19 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0017_alter_location_city"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ("-id",),
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
    ]
