name: Django CI

on:
  push:
    branches: [ "main" ]

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9.13, ]
        redis-version: [7, ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/dev.txt
    - name: Start Redis
      uses: supercharge/redis-github-action@1.6.0
      with:
        redis-version: ${{ matrix.redis-version }}
    - name: Run Tests
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DJANGO_SETTINGS_MODULE: 'config.settings.dev'
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        TEST: 1
      run: |
        pytest -vv -s 
